#配置程序端口，默认为8080
# 配置默认访问路径，默认为/
server:
  port: 8080
  servlet:
    context-path: /demo
    
mybatis:
  mapperLocations: classpath:mapper/**/*.xml
  typeAliasesPackage: com.example.model
  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/st_jsp?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Hongkong
    username: root
  mvc:
    view:
      prefix: /deng/
      suffix: .jsp

#  redis:
#      host: 127.0.0.1
#      database: 1
#      port: 6379
#      password: 123456
#      timeout: 1s
#      jedis:
#        pool:
#          max-active: 20
#          max-idle: 20
#          min-idle: 10
#          max-wait: -1ms
#  cache:
#    redis:

#      use-key-prefix: true
#      key-prefix: dev
#      cache-null-values: false
#      time-to-live: 20s     


      